-- Seed Artisans
INSERT INTO public.artisans (id, name, location, specialty, product_count, story, technique, heritage, img, process_img, tags, quote)
VALUES 
('weavers-of-bengal', 'Weavers of Bengal', 'West Bengal, India', 'Tant & Jamdani Weaving', '140+', 'For generations, the weavers of this collective have preserved the ancient art of Tant and Jamdani. Each thread is hand-spun and woven on traditional pit looms, a process that can take weeks for a single masterpiece.', 'Traditional Pit Loom Weaving', 'Over 200 years of communal weaving heritage, passed down from master to apprentice through oral tradition and hands-on practice.', '/artisans/bengal_weaver.png', 'https://images.unsplash.com/photo-1621259182978-f09e5e2ca1ff?auto=format&fit=crop&q=80&w=1600', ARRAY['Tant Cotton', 'Hand-spun', 'Heritage Art'], 'I believe that the objects we surround ourselves with should tell a story of time, patience, and human touch.'),
('rajesh-woodworks', 'Rajesh Woodworks', 'Saharanpur, Uttar Pradesh', 'Teakwood Inlay & Carving', '85+', 'Master Rajesh represents the pinnacle of Saharanpur''s woodworking tradition. His workshop specializes in the intricate ''Tarkashi'' technique—the art of inlaying fine brass or silver wire into hard wood.', 'Tarkashi Inlay Work', 'A family legacy starting from the royal courts, now adapted for modern home decor while maintaining imperial precision.', '/artisans/rajesh_woodworks.png', 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=1600', ARRAY['Teakwood', 'Brass Inlay', 'Imperial Craft'], 'Wood is a living canvas; our job is simply to reveal the history hidden within its grain.'),
('jaipur-collective', 'Jaipur Collective', 'Jaipur, Rajasthan', 'Blue Pottery & Hand-block Printing', '210+', 'The Jaipur Collective brings together the vibrant soul of Rajasthan. From the iconic cobalt-blue pottery to the rhythmic thumping of hand-block printing, every piece captures the desert''s enduring beauty.', 'Quartz-based Blue Pottery', 'Preserving the unique Turko-Persian origins of blue pottery that found its home in the Pink City during the 19th century.', '/artisans/jaipur_pottery.png', 'https://images.unsplash.com/photo-1565193998771-e6a2cd0606e9?auto=format&fit=crop&q=80&w=1600', ARRAY['Blue Pottery', 'Block Print', 'Royal Rajasthan'], 'In the cobalt of our pottery, we capture the spirit of the Rajasthani sky—endless and full of wonder.');

-- Seed Products
INSERT INTO public.products (id, name, price, original_price, rating, review_count, description, details, images, category, tag, artisan_id, is_custom, is_ready, is_natural)
VALUES
('heritage-jamdani-saree', 'Heritage Hand-woven Jamdani', 8500, NULL, 5.0, 42, 'A masterpiece of patience, this Jamdani saree features motifs woven directly into the loom.', ARRAY['Material: Pure Fine Cotton', 'Weave: Traditional Jamdani'], ARRAY['/products/earrings.png'], 'Textiles', 'Heritage', 'weavers-of-bengal', TRUE, FALSE, FALSE),
('resin-ocean-frame', 'Oceanic Resin Photo Frame', 899, NULL, 4.8, 124, 'A breathtaking handcrafted resin frame capturing the essence of ocean waves.', ARRAY['Material: Premium Epoxy Resin'], ARRAY['/products/mandala.png'], 'Resin Art', 'Best Seller', 'rajesh-woodworks', FALSE, TRUE, FALSE);
